//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceNoticesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceNoticesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.ServiceNoticesResources", typeof(ServiceNoticesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla Eklendi.
        /// </summary>
        public static string BasariylaEklendi {
            get {
                return ResourceManager.GetString("BasariylaEklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla Giriş yapıldı.
        /// </summary>
        public static string BasariylaGirisYapildi {
            get {
                return ResourceManager.GetString("BasariylaGirisYapildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla gönderildi..
        /// </summary>
        public static string BasariylaGonderildi {
            get {
                return ResourceManager.GetString("BasariylaGonderildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla Güncellendi.
        /// </summary>
        public static string BasariylaGuncellendi {
            get {
                return ResourceManager.GetString("BasariylaGuncellendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla Silindi.
        /// </summary>
        public static string BasariylaSilindi {
            get {
                return ResourceManager.GetString("BasariylaSilindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branşı silebilmek için, önce branşa bağlı sınıfları silmeniz gerekir..
        /// </summary>
        public static string BransiSilebilmekIcin {
            get {
                return ResourceManager.GetString("BransiSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ders Grubu silebilmek için, önce bağlı dersleri silmeniz gerekir..
        /// </summary>
        public static string DersGrupSilebilmekIcin {
            get {
                return ResourceManager.GetString("DersGrupSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dersi silebilmek için, derse bağlı öğrenciyi silmeniz gerekir..
        /// </summary>
        public static string DersiSilebilmekIcinOgrenciOzelDersSecim {
            get {
                return ResourceManager.GetString("DersiSilebilmekIcinOgrenciOzelDersSecim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dersi silebilmek için, önce bağlı personeli silmeniz gerekir..
        /// </summary>
        public static string DersiSilebilmekIcinPersonel {
            get {
                return ResourceManager.GetString("DersiSilebilmekIcinPersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dersi silebilmek için, önce bağlı yayını silmeniz gerekir..
        /// </summary>
        public static string DersiSilebilmekIcinYayin {
            get {
                return ResourceManager.GetString("DersiSilebilmekIcinYayin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dersliği silebilmek için, önce dersliğe bağlı sınıfları silmeniz gerekir..
        /// </summary>
        public static string DersligiSilebilmekIcin {
            get {
                return ResourceManager.GetString("DersligiSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Ödenecek Tutar.
        /// </summary>
        public static string EgitimUcretiAciklama {
            get {
                return ResourceManager.GetString("EgitimUcretiAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta ile kayıtlı personel bulunmaktadır. Eposta benzersiz olmalıdır..
        /// </summary>
        public static string EpostaIleKayitli {
            get {
                return ResourceManager.GetString("EpostaIleKayitli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Etkin değilse, İşten Ayrılma Tarihi boş olamaz..
        /// </summary>
        public static string EtkinDegilseIstenAyrilmaTarihiDoluOlmali {
            get {
                return ResourceManager.GetString("EtkinDegilseIstenAyrilmaTarihiDoluOlmali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinliği silebilmek için, önce bağlı sözleşmeleri silmeniz gerekir..
        /// </summary>
        public static string EtkinligiSilebilmekIcinBagliSozlesme {
            get {
                return ResourceManager.GetString("EtkinligiSilebilmekIcinBagliSozlesme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik eklerken, Danışman Personel seçmelisiniz..
        /// </summary>
        public static string EtkinlikIcinDanismanPersonelZorunlu {
            get {
                return ResourceManager.GetString("EtkinlikIcinDanismanPersonelZorunlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik için yeterli kontenjan yok..
        /// </summary>
        public static string EtkinlikIcinYeterliKontenjanYok {
            get {
                return ResourceManager.GetString("EtkinlikIcinYeterliKontenjanYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik için yeterli kapasite yok.
        /// </summary>
        public static string EtkinlikKapasiteYeterliDegil {
            get {
                return ResourceManager.GetString("EtkinlikKapasiteYeterliDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlik eklerken, Etkinlik seçmelisiniz..
        /// </summary>
        public static string EtkinlikSecmekZorunlu {
            get {
                return ResourceManager.GetString("EtkinlikSecmekZorunlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareketi olan Hesap silinemez..
        /// </summary>
        public static string HesapHareketOlanHesapSilinemez {
            get {
                return ResourceManager.GetString("HesapHareketOlanHesapSilinemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci, Personel ya da Şubeye ait hesap silinemez..
        /// </summary>
        public static string HesapSilinemezUyari {
            get {
                return ResourceManager.GetString("HesapSilinemezUyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim bilgilerinde, Ad veya Soyad boş olamaz. Boş olan :.
        /// </summary>
        public static string IletisimBilgilerindeAdSoyadBosOlamaz {
            get {
                return ResourceManager.GetString("IletisimBilgilerindeAdSoyadBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Tercihi olarak belirlenmiş yakının, Cep Telefonu alanı boş olamaz. Hatalı Bilgi :.
        /// </summary>
        public static string IletisimYakiniSeciliCepTelefonBosOlamaz {
            get {
                return ResourceManager.GetString("IletisimYakiniSeciliCepTelefonBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıyafet Beden silebilmek için, önce bağlı kıyafetleri silmeniz gerekir..
        /// </summary>
        public static string KiyafetBedenSilebilmekIcin {
            get {
                return ResourceManager.GetString("KiyafetBedenSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıyafet silebilmek için, önce bağlı sözleşmeleri silmeniz gerekir..
        /// </summary>
        public static string KiyafetSilebilmekIcin {
            get {
                return ResourceManager.GetString("KiyafetSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıyafet Tür silebilmek için, önce bağlı kıyafetleri silmeniz gerekir..
        /// </summary>
        public static string KiyafetTurSilebilmekIcin {
            get {
                return ResourceManager.GetString("KiyafetTurSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu silebilmek için, önce bağlı sınav soruları silmeniz gerekir..
        /// </summary>
        public static string KonuSilebilmekIcin {
            get {
                return ResourceManager.GetString("KonuSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Bulunamadı.
        /// </summary>
        public static string KullanicBbulunamadi {
            get {
                return ResourceManager.GetString("KullanicBbulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı ile kayıtlı personel bulunmaktadır. Kullanıcı adı benzersiz olmalıdır..
        /// </summary>
        public static string KullaniciAdiKullanilmis {
            get {
                return ResourceManager.GetString("KullaniciAdiKullanilmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı eklerken, en az bir tane yetkili olduğu şube belirlenmelidir..
        /// </summary>
        public static string KullaniciEklerkenYetkiliSubeSecilmelidir {
            get {
                return ResourceManager.GetString("KullaniciEklerkenYetkiliSubeSecilmelidir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı etkin değil.
        /// </summary>
        public static string KullanıcıEtkinDegil {
            get {
                return ResourceManager.GetString("KullanıcıEtkinDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı grubu silebilmek için, önce gruba bağlı kullanıcıları silmeniz gerekir..
        /// </summary>
        public static string KullaniciGrubuSilebilmekIcin {
            get {
                return ResourceManager.GetString("KullaniciGrubuSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı eklenirken, Yetki Grup seçimi zorunludur..
        /// </summary>
        public static string KullaniciPersonelGrupSecilmelidir {
            get {
                return ResourceManager.GetString("KullaniciPersonelGrupSecilmelidir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumu silebilmek için, önce kuruma bağlı sezonları silmeniz gerekir..
        /// </summary>
        public static string KurumuSilebilmekIcinSezonlar {
            get {
                return ResourceManager.GetString("KurumuSilebilmekIcinSezonlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumu silebilmek için, önce kuruma bağlı şubeleri silmeniz gerekir..
        /// </summary>
        public static string KurumuSilebilmekIcinSubeler {
            get {
                return ResourceManager.GetString("KurumuSilebilmekIcinSubeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nereden Duydunuz bilgisini silebilmek için, önce bağlı öğrencileri silmeniz gerekir..
        /// </summary>
        public static string NeredenDuydunuzuSilebilmekIcin {
            get {
                return ResourceManager.GetString("NeredenDuydunuzuSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taksit.
        /// </summary>
        public static string NoluTaksit {
            get {
                return ResourceManager.GetString("NoluTaksit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme için Hareket Tarihi girilmeli..
        /// </summary>
        public static string OdemeHareketTarihi {
            get {
                return ResourceManager.GetString("OdemeHareketTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenecek Hesap Seçilmeli!.
        /// </summary>
        public static string OdemeHesapSecilmeli {
            get {
                return ResourceManager.GetString("OdemeHesapSecilmeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenecek Hesap boş olamaz..
        /// </summary>
        public static string OdenecekHesapSeciliOlmali {
            get {
                return ResourceManager.GetString("OdenecekHesapSeciliOlmali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci bulunamadı!.
        /// </summary>
        public static string OgrenciBulunamadi {
            get {
                return ResourceManager.GetString("OgrenciBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci İletişim Tercihi olarak seçili. Cep Telefonu boş olamaz..
        /// </summary>
        public static string OgrenciIletisimTercihEdlineCepTelefonBosOlamaz {
            get {
                return ResourceManager.GetString("OgrenciIletisimTercihEdlineCepTelefonBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrencinin, T.C. Kimlik No veya kişisel bilgiler uyuşmuyor..
        /// </summary>
        public static string OgrenciTcKimlikHatali {
            get {
                return ResourceManager.GetString("OgrenciTcKimlikHatali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenciyi Ekleyen Personel silebilir..
        /// </summary>
        public static string OgrenciyiEkleyenPersonelSilebilir {
            get {
                return ResourceManager.GetString("OgrenciyiEkleyenPersonelSilebilir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optik Form Bilgi başarıyla güncellendi..
        /// </summary>
        public static string OptikFormBasariyla {
            get {
                return ResourceManager.GetString("OptikFormBasariyla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optik Form Bilgi ders tanımlamalar için önce Optik Form Bilgi kaydetmelisiniz..
        /// </summary>
        public static string OptikFormBilgiDersTanimlamalarIcin {
            get {
                return ResourceManager.GetString("OptikFormBilgiDersTanimlamalarIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optik Form Bilgi ders tanımlamalar başarıyla güncellendi..
        /// </summary>
        public static string OptikFormDersTanimlamaBasariyla {
            get {
                return ResourceManager.GetString("OptikFormDersTanimlamaBasariyla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optik Form silebilmek için, önce bağlı sınavları silmeniz gerekir..
        /// </summary>
        public static string OptikFormSilebilmekIcin {
            get {
                return ResourceManager.GetString("OptikFormSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi silebilmek için, önce birime bağlı şubeleri silmeniz gerekir..
        /// </summary>
        public static string ParaBirimiSilebilmekIcin {
            get {
                return ResourceManager.GetString("ParaBirimiSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Grubu silebilmek için, önce gruba bağlı personelleri silmeniz gerekir..
        /// </summary>
        public static string PersonelGrubuSilebilmekIcin {
            get {
                return ResourceManager.GetString("PersonelGrubuSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personelin Şubelerden aldığı ücret, maaşından yüksek olamaz..
        /// </summary>
        public static string PersonelinSubelerdenAldigiToplamMaasindanCokOlamaz {
            get {
                return ResourceManager.GetString("PersonelinSubelerdenAldigiToplamMaasindanCokOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personeli silebilmek için, Personele bağlı Hesabı silmeniz gerekir..
        /// </summary>
        public static string PersoneliSilebilmekIcinHesap {
            get {
                return ResourceManager.GetString("PersoneliSilebilmekIcinHesap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personeli silebilmek için, Personele bağlı Kullanıcıyı silmeniz gerekir..
        /// </summary>
        public static string PersoneliSilebilmekIcinKullanici {
            get {
                return ResourceManager.GetString("PersoneliSilebilmekIcinKullanici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Yetki Grubu silebilmek için, önce gruba bağlı personelleri silmeniz gerekir..
        /// </summary>
        public static string PersonelYetkiGrubuSilebilmekIcin {
            get {
                return ResourceManager.GetString("PersonelYetkiGrubuSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenen Peşinat.
        /// </summary>
        public static string PesinatAciklama {
            get {
                return ResourceManager.GetString("PesinatAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peşinat Ödeme için hesap seçmek zorunlu..
        /// </summary>
        public static string PesinatHesapSecmekZorunlu {
            get {
                return ResourceManager.GetString("PesinatHesapSecmekZorunlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peşinat Tutar minimum Peşinat oranın aldında. Peşinat Oran :.
        /// </summary>
        public static string PesinatTutarYeterliDegil {
            get {
                return ResourceManager.GetString("PesinatTutarYeterliDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehri silebilmek için, önce şehre bağlı ilçeleri silmeniz gerekir..
        /// </summary>
        public static string SehriSilebilmekIcinIlceler {
            get {
                return ResourceManager.GetString("SehriSilebilmekIcinIlceler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehri silebilmek için, önce şehre bağlı şubeleri silmeniz gerekir..
        /// </summary>
        public static string SehriSilebilmekIcinSubeler {
            get {
                return ResourceManager.GetString("SehriSilebilmekIcinSubeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seneti İmzalayan kişinin, Ad alanı boş olamaz..
        /// </summary>
        public static string SenetiImzalayanAdBosOlamaz {
            get {
                return ResourceManager.GetString("SenetiImzalayanAdBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seneti İmzalayan kişinin, Doğum Tarihi alanı boş olamaz..
        /// </summary>
        public static string SenetiImzalayanDogumTarihiBosOlamaz {
            get {
                return ResourceManager.GetString("SenetiImzalayanDogumTarihiBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seneti İmzalayan kişinin, Soyad alanı boş olamaz..
        /// </summary>
        public static string SenetiImzalayanSoyadBosOlamaz {
            get {
                return ResourceManager.GetString("SenetiImzalayanSoyadBosOlamaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis için yeterli Kapasite yok..
        /// </summary>
        public static string ServisIcinYeterliKapasiteYok {
            get {
                return ResourceManager.GetString("ServisIcinYeterliKapasiteYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisi silebilmek için, önce bağlı sözleşmeleri silmeniz gerekir..
        /// </summary>
        public static string ServisSilebilmekIcin {
            get {
                return ResourceManager.GetString("ServisSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sezonu silebilmek için, önce sezona bağlı sınıfları silmeniz gerekir..
        /// </summary>
        public static string SezonuSilebilmekIcin {
            get {
                return ResourceManager.GetString("SezonuSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sınav Tür silebilmek için, önce sınav türe bağlı sınavları silmeninz gerekir..
        /// </summary>
        public static string SinavTurSilebilmekIcin {
            get {
                return ResourceManager.GetString("SinavTurSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sınıf Seansı silebilmek için, önce seansa bağlı sınıfları silmeniz gerekir..
        /// </summary>
        public static string SinifSeansiSilebilmekIcin {
            get {
                return ResourceManager.GetString("SinifSeansiSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sınıf seçmek zorunlu..
        /// </summary>
        public static string SinifSecmekZorunlu {
            get {
                return ResourceManager.GetString("SinifSecmekZorunlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sınıf Seviyeyi silebilmek için, önce seviyeye bağlı sınıfları silmeniz gerekir..
        /// </summary>
        public static string SinifSeviyeSilebilmekIcin {
            get {
                return ResourceManager.GetString("SinifSeviyeSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sınıf Türü silebilmek için, önce türe bağlı sınıfları silmeniz gerekir..
        /// </summary>
        public static string SinifTurSilebilmekIcin {
            get {
                return ResourceManager.GetString("SinifTurSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Başlık bu aşamada değiştirilemez..
        /// </summary>
        public static string SmsHesapBaslikDegistirilemez {
            get {
                return ResourceManager.GetString("SmsHesapBaslikDegistirilemez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sözleşme Toplam Tutar.
        /// </summary>
        public static string SozlesmeToplamTutar {
            get {
                return ResourceManager.GetString("SozlesmeToplamTutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube seçimi yapmalısınız..
        /// </summary>
        public static string SubeSecmekZorunlu {
            get {
                return ResourceManager.GetString("SubeSecmekZorunlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubeyi silebilmek için, önce şubeye bağlı personelleri silmeniz gerekir..
        /// </summary>
        public static string SubeyiSilebilmekIcinPersoneller {
            get {
                return ResourceManager.GetString("SubeyiSilebilmekIcinPersoneller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubeyi silebilmek için, önce şubeye bağlı sınıfları silmeniz gerekir..
        /// </summary>
        public static string SubeyiSilebilmekIcinSiniflar {
            get {
                return ResourceManager.GetString("SubeyiSilebilmekIcinSiniflar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sınıfı silebilmek için, önce bağlı yetkilerden kaldırmanız gerekir..
        /// </summary>
        public static string SubeyiSilebilmekIcinYetkiler {
            get {
                return ResourceManager.GetString("SubeyiSilebilmekIcinYetkiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.C. Kimlik No veya kişisel bilgiler uyuşmuyor..
        /// </summary>
        public static string TcKimlikHatali {
            get {
                return ResourceManager.GetString("TcKimlikHatali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.C. Kimlik No ile kayıtlı personel bulunmaktadır. T.C. Kimlik No benzersiz olmalıdır..
        /// </summary>
        public static string TcKimlikIleKayitliPersonelMevcut {
            get {
                return ResourceManager.GetString("TcKimlikIleKayitliPersonelMevcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar, tutarların toplamına eşit olmalıdır..
        /// </summary>
        public static string ToplamTutarDogruDegil {
            get {
                return ResourceManager.GetString("ToplamTutarDogruDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar ile Taksitli Tutar eşit değil..
        /// </summary>
        public static string ToplamTutarIleTaksitliTutarEsitDegil {
            get {
                return ResourceManager.GetString("ToplamTutarIleTaksitliTutarEsitDegil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülkeyi silebilmek için, önce ülkeye bağlı şehirleri silmeniz gerekir..
        /// </summary>
        public static string UlkeyiSilebilmekIcin {
            get {
                return ResourceManager.GetString("UlkeyiSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varolan kaydı, tekrar ekleyemezsiniz..
        /// </summary>
        public static string VarolanKaydi {
            get {
                return ResourceManager.GetString("VarolanKaydi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayını silebilmek için, önce yayına bağlı öğrencileri silmeniz gerekir..
        /// </summary>
        public static string YayinSilebilmekIcin {
            get {
                return ResourceManager.GetString("YayinSilebilmekIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkisiz İşlem !.
        /// </summary>
        public static string YetkisizIslem {
            get {
                return ResourceManager.GetString("YetkisizIslem", resourceCulture);
            }
        }
    }
}
